// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// const SUPABASE_URL = "https://nwohehoountzfudzygqg.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53b2hlaG9vdW50emZ1ZHp5Z3FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODYwODgsImV4cCI6MjA2NzU2MjA4OH0.8MBoQn_Hs4uMf6ctCLcMr_vBqDAQ_YbglLYV9bet5pM";
const SUPABASE_URL = "https://wtwhyndtvxecpsyrpvll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0d2h5bmR0dnhlY3BzeXJwdmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTY0MDIsImV4cCI6MjA2OTk3MjQwMn0.7pVtVJ7oyykjRrry3ntef8wCavQJF13E0qm9LsDMcas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Prevent URL parsing that might cause issues
    flowType: 'pkce'
  },
  realtime: {
    params: {
      eventsPerSecond: 2 // Reduce realtime event frequency
    }
  }
});